# Generated by Django 2.0.7 on 2018-07-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_songcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcreate',
            name='album_logo',
            field=models.FileField(blank=True, null=True, upload_to='album/'),
        ),
    ]
