# Generated by Django 2.0.7 on 2018-07-26 19:04

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_auto_20180726_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcreate',
            name='album_logo',
            field=models.ImageField(default='F:/xyz.jpeg', upload_to=album.models.upload_image_path),
        ),
    ]
