# Generated by Django 2.0.7 on 2018-07-28 22:48

import album.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_songcreate_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcreate',
            name='album_logo',
            field=models.ImageField(default='/media/xyz.jpg', upload_to=album.models.upload_image_path),
        ),
    ]
